### ISSUE TITLE
Create cmd-nse-vl3-vpp

### ISSUE THREAD

**Issue by edwarnicke** [networkservicemesh/cmd-nse-vl3-vpp#1]
# vl3 nse

![image](https://user-images.githubusercontent.com/49399980/131915577-ea3a033b-222c-494b-a7cc-23cb1f23f69c.png)

## Description

Create an NSE for vl3.

In the first pass, simply create an NSE that, given a request, uses networkservicemesh/sdk-vpp#341 to create a cmd-nse-vl3-vpp.

For ipam, start by using point2pointipam (we will become more sophisticated as we go along).

In the table created by networkservicemesh/sdk-vpp#341 program routes (see https://github.com/networkservicemesh/sdk-vpp/tree/main/pkg/networkservice/connectioncontext/ipcontext/routes which may be usable as is, or we may need a more sophisticated approach)for all incoming connections.

**Comment by edwarnicke** [comment]
Note: this is a starting place, its a very simple single instance vL3.  Subsequent issues will specify enhancements to make it more sophisticated.

**Comment by denis-tingaikin** [comment]
This also can be useful https://docs.google.com/document/d/108QWsficn9adJrCppuHZcDi-AqlV7WFOaKKwYvIs-5k/edit#heading=h.1x2n7hnh1w8m

**Comment by denis-tingaikin** [comment]
@edwarnicke I think we also need to follow this https://drive.google.com/file/d/1eMIkdlav1WwGaTKRgTnkhQ95Ipqw29bu/view for registration vl3 NSEs on startup.

**Comment by denis-tingaikin** [comment]
@edwarnicke Should we also create an issue for `point2pointipam`?

**Comment by denis-tingaikin** [comment]
Chain of vl3 use
```go
point2pointipam.NewServer(ipnet),
routes.NewServer(), // program routes
iptable.NewServer(),
sendfd.NewServer(),
up.NewServer(ctx, vppConn),     
connectioncontext.NewServer(vppConn),  
tag.NewServer(ctx, vppConn),
mechanisms.NewServer(map[string]networkservice.NetworkServiceServer{            
memif.MECHANISM: memif.NewServer(vppConn) }),   
kernel.MECHANISM: ... ,
}, 
loopback.NewServer() // attach fib to the interface
```

**Comment by denis-tingaikin** [comment]
@edwarnicke Could you have a look?  ☝️

**Comment by edwarnicke** [comment]
@glazychev-art What is the status of this?
