### ISSUE TITLE
Add dual stack support 

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/cmd-nse-vl3-vpp#261]
### Description

Currently vL3-endpoint only support single stack:
https://github.com/networkservicemesh/cmd-nse-vl3-vpp/blob/main/main.go#L551

It would be useful to add dualStack support.
For example, cmd-nse-icmp-responder already supports it:
https://github.com/networkservicemesh/cmd-nse-icmp-responder/blob/main/main.go#L208

**Comment by denis-tingaikin** [comment]
The plan for implementing this could be:

1. deploy two vl3 ipams, one with ipv4 (as in the examples right now), the second with ipv6 prefixes
2. modify github.com/networkservicemesh/sdk/pkg/networkservice/connectioncontext/ipcontext/vl3 work with an array of prefixes exactly the same as in groupipam
3. covert this https://github.com/networkservicemesh/cmd-nse-vl3-vpp/blob/main/main.go#L113 to the list
4. add dualstack vl3 example for deployments-k8s

**Comment by VitalyGushin** [comment]
Integration Tests: https://github.com/networkservicemesh/cmd-nse-vl3-vpp/issues/261

**Comment by denis-tingaikin** [comment]
Seems like done.

@edwarnicke FYI: Now we can use dual stack for vl3 networks.
