### ISSUE TITLE
vL3 MTU

### ISSUE THREAD

**Issue by glazychev-art** [networkservicemesh/cmd-nse-vl3-vpp#77]
## Description
All elements in a vl3 network should have the same MTU

Example (NSC-1200 is a new client):

![vl3_NSE drawio](https://user-images.githubusercontent.com/17748275/174269669-dcb6bf61-89ed-4c76-9763-bee97dc15914.svg)

### For discussion:

**1**. Can we use **_IP fragmentation_**? In this case, it seems there are no problems with MTU. Am I wrong?
**2**. **_Dynamic update:_** In order to use the same MTU for the entire vl3 network, we need to add a `vl3MTU` chain element that will keep the minimum MTU for this network. _**Options**_:
&nbsp; **2a**. Updating values ​​in already existing elements (NSC, other vl3-NSE) will be carried out through **_refreshes_**. This will smoothly update the entire network and optimize with the new MTU value.
&nbsp; **2b**. Updating values ​​in already existing elements (NSC, other vl3-NSE) will be forced by sending a **_monitor event_** to the client. This will trigger a re-request. Probably, we need to implement a monitorClient (now there is only a [monitorServer](https://github.com/networkservicemesh/sdk/tree/main/pkg/networkservice/common/monitor)) and add it to the NSC

### Possible problems:
1. **_IP fragmentation_**: if we rely on fragmentation it will increase the load on vl3-NSE (overhead for the receiver when reassembling the fragments) 
2. What if we have a large, stable vl3 network (for example, MTU=1500), but at some point a new client with MTU=100 connects to this network. Should we completely reconfigure the entire network and reduce performance for each client (vl3 endpoint)?

**Comment by glazychev-art** [comment]
@edwarnicke 
Do you have any thoughts?

**Comment by glazychev-art** [comment]
@edwarnicke 
It's interesting idea to rely only on the healing. Let's take a closer look at this:

![vl3_mtu(2) drawio](https://user-images.githubusercontent.com/17748275/174557888-c9efea25-85f6-4c19-9f9f-c2d34a5eab92.svg)

If a new NSC-1-2 connects to vl3-NSE-1 with a different MTU - we need to update all MTUs:
1. NSC-1-1 will get DOWN event and start healing without reselect (DP is working fine)
2. But vl3-NSE-2 doesn't have a heal client due to vl3 specifics - all vl3-endpoints are connected to each other and if one of them is recreated, it will automatically connect to the previous ones. Thus, we will need to monitor the DOWN event from the application (not from the chain elements).

**Comment by edwarnicke** [comment]
@glazychev-art 

I'm not suggesting we *actually* use healing.  My point is that we already, in support of healing, propagate events back the chain to the NSC.

What I'm suggesting is considering a new 'state' value (or perhaps new filed) that indicates "REFRESH_REQUESTED" that, when it arrives at the NSC, results in a rerequest.   No no closing existing connections, no reselection, just a normal Refresh, but requested from *upstream*.

**Comment by glazychev-art** [comment]
All PRs for this issue were merged
